- name: All avaliable hosts
  hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql
        - postgresql-server

    - name: "Install Python packages"
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - psycopg2-binary

  tasks:
    - name: Find out if PostgreSQL is initialized
      ansible.builtin.stat:
        path: /var/lib/pgsql/data/pg_hba.conf
      register: postgres_data

    - name: Initialize PostgreSQL
      ansible.builtin.command: postgresql-setup initdb
      changed_when:
        not postgres_data.stat.exists

    - name: Start and enable services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - postgresql

  handlers:
    - name: Restart Postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted